<!DOCTYPE html>
<html>
	<head>
		<title>55097650 Assignment-3</title> 
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" href="main.css">
		
	</head>
	<body>
	
		<div id="wrapper">
		
			<header>
				
					 <div class="header">
						<img src="./pictures/logo.png" alt="logo" ">
					 </div>
					
					
			</header>
			
	
			<nav>
					<ul class="main_menue">
						<li><a href =index.php>***Home***</a></li>   
						<li><a href =about.php>About Us</a></li>
					 	
						<li><a href =contact.php>Contact Us </a></li> 
						<li><a href =register.php>Register</a> </li>  
						<li><a href =login.php>   ***Login***   </a></li>
					</ul>		
			
			</nav>
			<br>

		</div> 
	</body>
	
	
	

</html>




